# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npost.proto\x12\rddia.chapter4\"_\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12\x11\n\tauthor_id\x18\x04 \x01(\t\x12\r\n\x05likes\x18\x05 \x01(\x05\x12\x0c\n\x04tags\x18\x06 \x03(\t\",\n\x06PostDB\x12\"\n\x05posts\x18\x01 \x03(\x0b\x32\x13.ddia.chapter4.Post\"\x11\n\x0fGetPostsRequest\" \n\x12GetPostByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t2\xd6\x01\n\x0cPostsService\x12\x43\n\x08GetPosts\x12\x1e.ddia.chapter4.GetPostsRequest\x1a\x15.ddia.chapter4.PostDB\"\x00\x12G\n\x0bGetPostById\x12!.ddia.chapter4.GetPostByIdRequest\x1a\x13.ddia.chapter4.Post\"\x00\x12\x38\n\nCreatePost\x12\x13.ddia.chapter4.Post\x1a\x13.ddia.chapter4.Post\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POST._serialized_start=29
  _POST._serialized_end=124
  _POSTDB._serialized_start=126
  _POSTDB._serialized_end=170
  _GETPOSTSREQUEST._serialized_start=172
  _GETPOSTSREQUEST._serialized_end=189
  _GETPOSTBYIDREQUEST._serialized_start=191
  _GETPOSTBYIDREQUEST._serialized_end=223
  _POSTSSERVICE._serialized_start=226
  _POSTSSERVICE._serialized_end=440
# @@protoc_insertion_point(module_scope)
